services:
  caddy:
    image: balaji119/flowiq-caddy:v1
    env_file:
      - ./.env.production
    depends_on:
      - web
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./storage:/shared-storage:ro
    restart: unless-stopped

  postgres:
    image: postgres:16-bookworm
    env_file:
      - ./.env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-flowiq}
      POSTGRES_USER: ${POSTGRES_USER:-flowiq}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: balaji119/flowiq-web:v1
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: unless-stopped

  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    image: balaji119/flowiq-api:v1
    env_file:
      - ./.env.production
    environment:
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL:-postgres://flowiq:change-me@postgres:5432/flowiq?sslmode=disable}
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:
  postgres-data:
